[package]
name = "libudev_macro"
version = "1.1.0"
edition = "2021"

[lib]
name = "libudev_macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2.0.39", features = ["full", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"
