[package]
name = "random_seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libutils = { path = "../../libs/libutils" }
nix = "0.24"
libc = "0.2.*"
log = "0.4"
xattr = "0.2.3"
